/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BadgeColor, BadgeShape, BadgeSize, BadgeVariant, BreadcrumbEventDetail, BreadcrumbSeparator, ButtonEventDetail, ButtonGroupEventDetail, ButtonGroupOrientation, ButtonGroupSize, ButtonGroupVariant, ButtonRounded, ButtonSize, ButtonVariant, IconName, ToastLifecycleDetail, ToastPromiseOptions, ToastShowOptions } from "@karan9186/core";
import { DatePickerParser } from "./components/ui-date-picker/ui-date-picker";
import { DropdownMode, DropdownOption, DropdownVariant } from "./components/ui-dropdown/ui-dropdown";
import { IconName as IconName1 } from "./components/icons/icon.registry";
import { PanelRounded, PanelSize, PanelVariant } from "./components/ui-panel/ui-panel";
export { BadgeColor, BadgeShape, BadgeSize, BadgeVariant, BreadcrumbEventDetail, BreadcrumbSeparator, ButtonEventDetail, ButtonGroupEventDetail, ButtonGroupOrientation, ButtonGroupSize, ButtonGroupVariant, ButtonRounded, ButtonSize, ButtonVariant, IconName, ToastLifecycleDetail, ToastPromiseOptions, ToastShowOptions } from "@karan9186/core";
export { DatePickerParser } from "./components/ui-date-picker/ui-date-picker";
export { DropdownMode, DropdownOption, DropdownVariant } from "./components/ui-dropdown/ui-dropdown";
export { IconName as IconName1 } from "./components/icons/icon.registry";
export { PanelRounded, PanelSize, PanelVariant } from "./components/ui-panel/ui-panel";
export namespace Components {
    /**
     * UI Badge Component
     * Modern badge component with multiple variants, colors, and sizes
     * Supports icon slot, dot mode, and removable functionality
     * @event remove - Emitted when the remove button is clicked
     */
    interface UiBadge {
        /**
          * Color theme of the badge
          * @default 'primary'
         */
        "color": BadgeColor;
        /**
          * Disable the badge
          * @default false
         */
        "disabled": boolean;
        /**
          * Show as a dot indicator (status indicator)
          * @default false
         */
        "dot": boolean;
        /**
          * Show remove button
          * @default false
         */
        "removable": boolean;
        /**
          * Shape of the badge
          * @default 'rounded'
         */
        "shape": BadgeShape;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size": BadgeSize;
        /**
          * Visual style variant of the badge
          * @default 'solid'
         */
        "variant": BadgeVariant;
    }
    interface UiBreadcrumb {
        /**
          * Whether the breadcrumb is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Breadcrumb items as JSON string
          * @default ''
         */
        "items": string;
        /**
          * Number of items to show after collapse indicator
          * @default 1
         */
        "itemsAfterCollapse": number;
        /**
          * Number of items to show before collapse indicator
          * @default 1
         */
        "itemsBeforeCollapse": number;
        /**
          * Maximum number of items before collapsing
          * @default undefined (no collapse)
         */
        "maxItems"?: string;
        /**
          * Separator between items
          * @default 'slash'
         */
        "separator": BreadcrumbSeparator;
    }
    /**
     * UI Button Component
     * Modern button component with shadcn/ui inspired variants
     * Supports multiple sizes, states, and animations
     * @event uiClick - Emitted when button is clicked (not disabled/loading)
     * @event uiFocus - Emitted when button receives focus
     * @event uiBlur - Emitted when button loses focus
     */
    interface UiButton {
        /**
          * Whether to enable click animation (press effect)
          * @default false
         */
        "animated": boolean;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the button should take full width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Icon name for center (for icon-only buttons)
         */
        "icon"?: IconName;
        /**
          * Icon name for left side (from lucide icons)
         */
        "iconLeft"?: IconName;
        /**
          * Icon name for right side (from lucide icons)
         */
        "iconRight"?: IconName;
        /**
          * Whether the button is in loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Border radius size
          * @default 'md'
         */
        "rounded": ButtonRounded;
        /**
          * Size of the button
          * @default 'default'
         */
        "size": ButtonSize;
        /**
          * Visual style variant of the button
          * @default 'default'
         */
        "variant": ButtonVariant;
    }
    /**
     * UI ButtonGroup Component
     * Groups buttons together with layout control and selection logic
     * Composes existing Button components without duplicating logic
     * @event uiChange - Emitted when selection changes (if selectionMode is not 'none')
     * @event uiClick - Proxy for child button click events (optional)
     */
    interface UiButtonGroup {
        /**
          * Whether to enable click animation on child buttons (press effect)
          * @default false
         */
        "buttonAnimated": boolean;
        /**
          * Whether child buttons should take full width
          * @default false
         */
        "buttonFullWidth": boolean;
        /**
          * Whether child buttons are in loading state
          * @default false
         */
        "buttonLoading": boolean;
        /**
          * JSON string array of button objects with value, label, and optional button props If provided, buttons will be rendered automatically. Otherwise, use slot.
         */
        "buttons"?: string;
        /**
          * Whether the entire group is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the group takes full width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Gap between buttons
          * @default 'md'
         */
        "gap": 'xs' | 'sm' | 'md' | 'lg' | 'none';
        /**
          * Orientation of the button group
          * @default 'horizontal'
         */
        "orientation": ButtonGroupOrientation;
        /**
          * Border radius size for the button group
          * @default 'md'
         */
        "rounded": ButtonRounded;
        /**
          * Whether buttons are segmented (no gaps, shared borders)
          * @default false
         */
        "segmented": boolean;
        /**
          * Selection mode for the button group
          * @default 'none'
         */
        "selectionMode": 'none' | 'single' | 'multiple';
        /**
          * Size inheritance for child buttons
          * @default 'inherit'
         */
        "size": ButtonGroupSize;
        /**
          * Current selected value(s) - For single mode: string - For multiple mode: string[] - For none mode: undefined
         */
        "value"?: string | string[];
        /**
          * Variant inheritance for child buttons
          * @default 'inherit'
         */
        "variant": ButtonGroupVariant;
    }
    interface UiCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface UiDatePicker {
        "customParsers"?: DatePickerParser[];
        /**
          * @default 220
         */
        "debounce": number;
        /**
          * @default false
         */
        "defaultOpen": boolean;
        "defaultValue"?: Date | DateRangeValue | null;
        /**
          * @default false
         */
        "disabled": boolean;
        "icon"?: string;
        /**
          * @default false
         */
        "iconOnly": boolean;
        "label"?: string;
        /**
          * @default false
         */
        "loading": boolean;
        "maxDate"?: Date;
        "maxYear"?: number;
        "minDate"?: Date;
        "minYear"?: number;
        /**
          * @default 'single'
         */
        "mode": DatePickerMode;
        "open"?: boolean;
        /**
          * @default 'Enter date (e.g. 1 Jan 2020)'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "search": boolean;
        /**
          * @default false
         */
        "showActions": boolean;
        /**
          * @default true
         */
        "showIcon": boolean;
        "value"?: Date | DateRangeValue | null;
    }
    interface UiDropdown {
        /**
          * @default false
         */
        "clearable": boolean;
        /**
          * @default null
         */
        "defaultValue": any;
        /**
          * @default false
         */
        "disabled": boolean;
        "label"?: string;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default '300px'
         */
        "maxHeight": string;
        /**
          * @default 'none'
         */
        "maxWidth": string;
        /**
          * @default '200px'
         */
        "minWidth": string;
        /**
          * @default 'single'
         */
        "mode": DropdownMode;
        /**
          * @default undefined
         */
        "open": boolean;
        /**
          * @default []
         */
        "options": DropdownOption[];
        /**
          * @default 'Select...'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "searchable": boolean;
        /**
          * @default false
         */
        "selectAll": boolean;
        /**
          * @default undefined
         */
        "value": any;
        /**
          * @default 'input'
         */
        "variant": DropdownVariant;
    }
    interface UiIcon {
        /**
          * @default 'currentColor'
         */
        "color": string;
        "name": IconName1;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 2
         */
        "stroke": number;
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "icon"?: string;
        /**
          * @default 'Input icon action'
         */
        "iconAriaLabel": string;
        "label"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default 'md'
         */
        "rounded": 'xs' | 'sm' | 'md' | 'xl';
        /**
          * @default 'text'
         */
        "type": 'text' | 'number';
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiPanel {
        /**
          * Collapse the panel
         */
        "collapse": () => Promise<void>;
        /**
          * Whether the panel is collapsible
          * @default false
         */
        "collapsible": boolean;
        /**
          * Whether the panel is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Expand the panel
         */
        "expand": () => Promise<void>;
        /**
          * Expanded state (can be controlled or uncontrolled)
          * @default true
         */
        "expanded": boolean;
        /**
          * Renders body/footer only when expanded
          * @default false
         */
        "lazy": boolean;
        /**
          * Whether the panel is in loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Border radius of the panel
          * @default 'md'
         */
        "rounded": PanelRounded;
        /**
          * Size of the panel
          * @default 'md'
         */
        "size": PanelSize;
        /**
          * Keeps header visible while scrolling panel content
          * @default false
         */
        "stickyHeader": boolean;
        /**
          * Toggle the panel expand/collapse state
         */
        "toggle": () => Promise<void>;
        /**
          * Visual variant of the panel
          * @default 'default'
         */
        "variant": PanelVariant;
    }
    interface UiToast {
        "defaultDuration": number;
        "dismiss": (id?: string) => Promise<void>;
        "maxVisible": number;
        "pauseOnHover": boolean;
        "promise": <T>(promise: Promise<T>, options: ToastPromiseOptions) => Promise<string>;
        "show": (options: ToastShowOptions) => Promise<string>;
        "stackGap": number;
        "swipeDismiss": boolean;
    }
    interface UiToggle {
        "checked"?: boolean;
        /**
          * @default false
         */
        "defaultChecked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface UiBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiBadgeElement;
}
export interface UiBreadcrumbCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiBreadcrumbElement;
}
export interface UiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiButtonElement;
}
export interface UiButtonGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiButtonGroupElement;
}
export interface UiCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCheckboxElement;
}
export interface UiDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiDatePickerElement;
}
export interface UiDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiDropdownElement;
}
export interface UiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiInputElement;
}
export interface UiPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiPanelElement;
}
export interface UiToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiToastElement;
}
export interface UiToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiToggleElement;
}
declare global {
    interface HTMLUiBadgeElementEventMap {
        "remove": void;
    }
    /**
     * UI Badge Component
     * Modern badge component with multiple variants, colors, and sizes
     * Supports icon slot, dot mode, and removable functionality
     * @event remove - Emitted when the remove button is clicked
     */
    interface HTMLUiBadgeElement extends Components.UiBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiBadgeElementEventMap>(type: K, listener: (this: HTMLUiBadgeElement, ev: UiBadgeCustomEvent<HTMLUiBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiBadgeElementEventMap>(type: K, listener: (this: HTMLUiBadgeElement, ev: UiBadgeCustomEvent<HTMLUiBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiBadgeElement: {
        prototype: HTMLUiBadgeElement;
        new (): HTMLUiBadgeElement;
    };
    interface HTMLUiBreadcrumbElementEventMap {
        "uiClick": BreadcrumbEventDetail;
    }
    interface HTMLUiBreadcrumbElement extends Components.UiBreadcrumb, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiBreadcrumbElementEventMap>(type: K, listener: (this: HTMLUiBreadcrumbElement, ev: UiBreadcrumbCustomEvent<HTMLUiBreadcrumbElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiBreadcrumbElementEventMap>(type: K, listener: (this: HTMLUiBreadcrumbElement, ev: UiBreadcrumbCustomEvent<HTMLUiBreadcrumbElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiBreadcrumbElement: {
        prototype: HTMLUiBreadcrumbElement;
        new (): HTMLUiBreadcrumbElement;
    };
    interface HTMLUiButtonElementEventMap {
        "uiClick": ButtonEventDetail;
        "uiFocus": void;
        "uiBlur": void;
    }
    /**
     * UI Button Component
     * Modern button component with shadcn/ui inspired variants
     * Supports multiple sizes, states, and animations
     * @event uiClick - Emitted when button is clicked (not disabled/loading)
     * @event uiFocus - Emitted when button receives focus
     * @event uiBlur - Emitted when button loses focus
     */
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiButtonElementEventMap>(type: K, listener: (this: HTMLUiButtonElement, ev: UiButtonCustomEvent<HTMLUiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiButtonElementEventMap>(type: K, listener: (this: HTMLUiButtonElement, ev: UiButtonCustomEvent<HTMLUiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiButtonGroupElementEventMap {
        "valueChange": string | string[];
        "uiChange": ButtonGroupEventDetail;
        "uiClick": ButtonGroupEventDetail;
    }
    /**
     * UI ButtonGroup Component
     * Groups buttons together with layout control and selection logic
     * Composes existing Button components without duplicating logic
     * @event uiChange - Emitted when selection changes (if selectionMode is not 'none')
     * @event uiClick - Proxy for child button click events (optional)
     */
    interface HTMLUiButtonGroupElement extends Components.UiButtonGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiButtonGroupElementEventMap>(type: K, listener: (this: HTMLUiButtonGroupElement, ev: UiButtonGroupCustomEvent<HTMLUiButtonGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiButtonGroupElementEventMap>(type: K, listener: (this: HTMLUiButtonGroupElement, ev: UiButtonGroupCustomEvent<HTMLUiButtonGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiButtonGroupElement: {
        prototype: HTMLUiButtonGroupElement;
        new (): HTMLUiButtonGroupElement;
    };
    interface HTMLUiCheckboxElementEventMap {
        "uiChange": boolean;
        "uiBlur": void;
    }
    interface HTMLUiCheckboxElement extends Components.UiCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCheckboxElementEventMap>(type: K, listener: (this: HTMLUiCheckboxElement, ev: UiCheckboxCustomEvent<HTMLUiCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCheckboxElementEventMap>(type: K, listener: (this: HTMLUiCheckboxElement, ev: UiCheckboxCustomEvent<HTMLUiCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCheckboxElement: {
        prototype: HTMLUiCheckboxElement;
        new (): HTMLUiCheckboxElement;
    };
    interface HTMLUiDatePickerElementEventMap {
        "onChange": Date | DateRangeValue;
        "onApply": Date | DateRangeValue;
        "onCancel": void;
        "onInputChange": string;
        "onOpenChange": boolean;
        "onInvalidInput": string;
        "onFocus": void;
        "onBlur": void;
    }
    interface HTMLUiDatePickerElement extends Components.UiDatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiDatePickerElementEventMap>(type: K, listener: (this: HTMLUiDatePickerElement, ev: UiDatePickerCustomEvent<HTMLUiDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiDatePickerElementEventMap>(type: K, listener: (this: HTMLUiDatePickerElement, ev: UiDatePickerCustomEvent<HTMLUiDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiDatePickerElement: {
        prototype: HTMLUiDatePickerElement;
        new (): HTMLUiDatePickerElement;
    };
    interface HTMLUiDropdownElementEventMap {
        "valueChange": any;
        "openChange": boolean;
        "search": string;
    }
    interface HTMLUiDropdownElement extends Components.UiDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiDropdownElementEventMap>(type: K, listener: (this: HTMLUiDropdownElement, ev: UiDropdownCustomEvent<HTMLUiDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiDropdownElementEventMap>(type: K, listener: (this: HTMLUiDropdownElement, ev: UiDropdownCustomEvent<HTMLUiDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiDropdownElement: {
        prototype: HTMLUiDropdownElement;
        new (): HTMLUiDropdownElement;
    };
    interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {
    }
    var HTMLUiIconElement: {
        prototype: HTMLUiIconElement;
        new (): HTMLUiIconElement;
    };
    interface HTMLUiInputElementEventMap {
        "valueChange": string;
        "uiBlur": void;
        "uiIconClick": void;
    }
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiPanelElementEventMap {
        "toggle": boolean;
        "expand": boolean;
        "collapse": boolean;
        "uiToggle": { expanded: boolean };
    }
    interface HTMLUiPanelElement extends Components.UiPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiPanelElementEventMap>(type: K, listener: (this: HTMLUiPanelElement, ev: UiPanelCustomEvent<HTMLUiPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiPanelElementEventMap>(type: K, listener: (this: HTMLUiPanelElement, ev: UiPanelCustomEvent<HTMLUiPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiPanelElement: {
        prototype: HTMLUiPanelElement;
        new (): HTMLUiPanelElement;
    };
    interface HTMLUiToastElementEventMap {
        "toastShow": ToastLifecycleDetail;
        "toastClose": ToastLifecycleDetail;
    }
    interface HTMLUiToastElement extends Components.UiToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiToastElementEventMap>(type: K, listener: (this: HTMLUiToastElement, ev: UiToastCustomEvent<HTMLUiToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiToastElementEventMap>(type: K, listener: (this: HTMLUiToastElement, ev: UiToastCustomEvent<HTMLUiToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiToastElement: {
        prototype: HTMLUiToastElement;
        new (): HTMLUiToastElement;
    };
    interface HTMLUiToggleElementEventMap {
        "toggleChange": boolean;
    }
    interface HTMLUiToggleElement extends Components.UiToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiToggleElementEventMap>(type: K, listener: (this: HTMLUiToggleElement, ev: UiToggleCustomEvent<HTMLUiToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiToggleElementEventMap>(type: K, listener: (this: HTMLUiToggleElement, ev: UiToggleCustomEvent<HTMLUiToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiToggleElement: {
        prototype: HTMLUiToggleElement;
        new (): HTMLUiToggleElement;
    };
    interface HTMLElementTagNameMap {
        "ui-badge": HTMLUiBadgeElement;
        "ui-breadcrumb": HTMLUiBreadcrumbElement;
        "ui-button": HTMLUiButtonElement;
        "ui-button-group": HTMLUiButtonGroupElement;
        "ui-checkbox": HTMLUiCheckboxElement;
        "ui-date-picker": HTMLUiDatePickerElement;
        "ui-dropdown": HTMLUiDropdownElement;
        "ui-icon": HTMLUiIconElement;
        "ui-input": HTMLUiInputElement;
        "ui-panel": HTMLUiPanelElement;
        "ui-toast": HTMLUiToastElement;
        "ui-toggle": HTMLUiToggleElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * UI Badge Component
     * Modern badge component with multiple variants, colors, and sizes
     * Supports icon slot, dot mode, and removable functionality
     * @event remove - Emitted when the remove button is clicked
     */
    interface UiBadge {
        /**
          * Color theme of the badge
          * @default 'primary'
         */
        "color"?: BadgeColor;
        /**
          * Disable the badge
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Show as a dot indicator (status indicator)
          * @default false
         */
        "dot"?: boolean;
        /**
          * Emitted when the remove button is clicked
         */
        "onRemove"?: (event: UiBadgeCustomEvent<void>) => void;
        /**
          * Show remove button
          * @default false
         */
        "removable"?: boolean;
        /**
          * Shape of the badge
          * @default 'rounded'
         */
        "shape"?: BadgeShape;
        /**
          * Size of the badge
          * @default 'md'
         */
        "size"?: BadgeSize;
        /**
          * Visual style variant of the badge
          * @default 'solid'
         */
        "variant"?: BadgeVariant;
    }
    interface UiBreadcrumb {
        /**
          * Whether the breadcrumb is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Breadcrumb items as JSON string
          * @default ''
         */
        "items"?: string;
        /**
          * Number of items to show after collapse indicator
          * @default 1
         */
        "itemsAfterCollapse"?: number;
        /**
          * Number of items to show before collapse indicator
          * @default 1
         */
        "itemsBeforeCollapse"?: number;
        /**
          * Maximum number of items before collapsing
          * @default undefined (no collapse)
         */
        "maxItems"?: string;
        /**
          * Emitted when a breadcrumb item is clicked
         */
        "onUiClick"?: (event: UiBreadcrumbCustomEvent<BreadcrumbEventDetail>) => void;
        /**
          * Separator between items
          * @default 'slash'
         */
        "separator"?: BreadcrumbSeparator;
    }
    /**
     * UI Button Component
     * Modern button component with shadcn/ui inspired variants
     * Supports multiple sizes, states, and animations
     * @event uiClick - Emitted when button is clicked (not disabled/loading)
     * @event uiFocus - Emitted when button receives focus
     * @event uiBlur - Emitted when button loses focus
     */
    interface UiButton {
        /**
          * Whether to enable click animation (press effect)
          * @default false
         */
        "animated"?: boolean;
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the button should take full width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Icon name for center (for icon-only buttons)
         */
        "icon"?: IconName;
        /**
          * Icon name for left side (from lucide icons)
         */
        "iconLeft"?: IconName;
        /**
          * Icon name for right side (from lucide icons)
         */
        "iconRight"?: IconName;
        /**
          * Whether the button is in loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when button loses focus
         */
        "onUiBlur"?: (event: UiButtonCustomEvent<void>) => void;
        /**
          * Emitted when button is clicked (when not disabled or loading)
         */
        "onUiClick"?: (event: UiButtonCustomEvent<ButtonEventDetail>) => void;
        /**
          * Emitted when button receives focus
         */
        "onUiFocus"?: (event: UiButtonCustomEvent<void>) => void;
        /**
          * Border radius size
          * @default 'md'
         */
        "rounded"?: ButtonRounded;
        /**
          * Size of the button
          * @default 'default'
         */
        "size"?: ButtonSize;
        /**
          * Visual style variant of the button
          * @default 'default'
         */
        "variant"?: ButtonVariant;
    }
    /**
     * UI ButtonGroup Component
     * Groups buttons together with layout control and selection logic
     * Composes existing Button components without duplicating logic
     * @event uiChange - Emitted when selection changes (if selectionMode is not 'none')
     * @event uiClick - Proxy for child button click events (optional)
     */
    interface UiButtonGroup {
        /**
          * Whether to enable click animation on child buttons (press effect)
          * @default false
         */
        "buttonAnimated"?: boolean;
        /**
          * Whether child buttons should take full width
          * @default false
         */
        "buttonFullWidth"?: boolean;
        /**
          * Whether child buttons are in loading state
          * @default false
         */
        "buttonLoading"?: boolean;
        /**
          * JSON string array of button objects with value, label, and optional button props If provided, buttons will be rendered automatically. Otherwise, use slot.
         */
        "buttons"?: string;
        /**
          * Whether the entire group is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the group takes full width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Gap between buttons
          * @default 'md'
         */
        "gap"?: 'xs' | 'sm' | 'md' | 'lg' | 'none';
        /**
          * Emitted when selection changes (legacy event for backward compatibility)
         */
        "onUiChange"?: (event: UiButtonGroupCustomEvent<ButtonGroupEventDetail>) => void;
        /**
          * Proxy for child button click events
         */
        "onUiClick"?: (event: UiButtonGroupCustomEvent<ButtonGroupEventDetail>) => void;
        /**
          * Emitted when value changes
         */
        "onValueChange"?: (event: UiButtonGroupCustomEvent<string | string[]>) => void;
        /**
          * Orientation of the button group
          * @default 'horizontal'
         */
        "orientation"?: ButtonGroupOrientation;
        /**
          * Border radius size for the button group
          * @default 'md'
         */
        "rounded"?: ButtonRounded;
        /**
          * Whether buttons are segmented (no gaps, shared borders)
          * @default false
         */
        "segmented"?: boolean;
        /**
          * Selection mode for the button group
          * @default 'none'
         */
        "selectionMode"?: 'none' | 'single' | 'multiple';
        /**
          * Size inheritance for child buttons
          * @default 'inherit'
         */
        "size"?: ButtonGroupSize;
        /**
          * Current selected value(s) - For single mode: string - For multiple mode: string[] - For none mode: undefined
         */
        "value"?: string | string[];
        /**
          * Variant inheritance for child buttons
          * @default 'inherit'
         */
        "variant"?: ButtonGroupVariant;
    }
    interface UiCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        "onUiBlur"?: (event: UiCheckboxCustomEvent<void>) => void;
        "onUiChange"?: (event: UiCheckboxCustomEvent<boolean>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface UiDatePicker {
        "customParsers"?: DatePickerParser[];
        /**
          * @default 220
         */
        "debounce"?: number;
        /**
          * @default false
         */
        "defaultOpen"?: boolean;
        "defaultValue"?: Date | DateRangeValue | null;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "icon"?: string;
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        "label"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        "maxDate"?: Date;
        "maxYear"?: number;
        "minDate"?: Date;
        "minYear"?: number;
        /**
          * @default 'single'
         */
        "mode"?: DatePickerMode;
        "onOnApply"?: (event: UiDatePickerCustomEvent<Date | DateRangeValue>) => void;
        "onOnBlur"?: (event: UiDatePickerCustomEvent<void>) => void;
        "onOnCancel"?: (event: UiDatePickerCustomEvent<void>) => void;
        "onOnChange"?: (event: UiDatePickerCustomEvent<Date | DateRangeValue>) => void;
        "onOnFocus"?: (event: UiDatePickerCustomEvent<void>) => void;
        "onOnInputChange"?: (event: UiDatePickerCustomEvent<string>) => void;
        "onOnInvalidInput"?: (event: UiDatePickerCustomEvent<string>) => void;
        "onOnOpenChange"?: (event: UiDatePickerCustomEvent<boolean>) => void;
        "open"?: boolean;
        /**
          * @default 'Enter date (e.g. 1 Jan 2020)'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "search"?: boolean;
        /**
          * @default false
         */
        "showActions"?: boolean;
        /**
          * @default true
         */
        "showIcon"?: boolean;
        "value"?: Date | DateRangeValue | null;
    }
    interface UiDropdown {
        /**
          * @default false
         */
        "clearable"?: boolean;
        /**
          * @default null
         */
        "defaultValue"?: any;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default '300px'
         */
        "maxHeight"?: string;
        /**
          * @default 'none'
         */
        "maxWidth"?: string;
        /**
          * @default '200px'
         */
        "minWidth"?: string;
        /**
          * @default 'single'
         */
        "mode"?: DropdownMode;
        "onOpenChange"?: (event: UiDropdownCustomEvent<boolean>) => void;
        "onSearch"?: (event: UiDropdownCustomEvent<string>) => void;
        "onValueChange"?: (event: UiDropdownCustomEvent<any>) => void;
        /**
          * @default undefined
         */
        "open"?: boolean;
        /**
          * @default []
         */
        "options"?: DropdownOption[];
        /**
          * @default 'Select...'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "searchable"?: boolean;
        /**
          * @default false
         */
        "selectAll"?: boolean;
        /**
          * @default undefined
         */
        "value"?: any;
        /**
          * @default 'input'
         */
        "variant"?: DropdownVariant;
    }
    interface UiIcon {
        /**
          * @default 'currentColor'
         */
        "color"?: string;
        "name": IconName1;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 2
         */
        "stroke"?: number;
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "icon"?: string;
        /**
          * @default 'Input icon action'
         */
        "iconAriaLabel"?: string;
        "label"?: string;
        "onUiBlur"?: (event: UiInputCustomEvent<void>) => void;
        "onUiIconClick"?: (event: UiInputCustomEvent<void>) => void;
        "onValueChange"?: (event: UiInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "rounded"?: 'xs' | 'sm' | 'md' | 'xl';
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'number';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiPanel {
        /**
          * Whether the panel is collapsible
          * @default false
         */
        "collapsible"?: boolean;
        /**
          * Whether the panel is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Expanded state (can be controlled or uncontrolled)
          * @default true
         */
        "expanded"?: boolean;
        /**
          * Renders body/footer only when expanded
          * @default false
         */
        "lazy"?: boolean;
        /**
          * Whether the panel is in loading state
          * @default false
         */
        "loading"?: boolean;
        "onCollapse"?: (event: UiPanelCustomEvent<boolean>) => void;
        "onExpand"?: (event: UiPanelCustomEvent<boolean>) => void;
        /**
          * Emitted when panel is expanded/collapsed
         */
        "onToggle"?: (event: UiPanelCustomEvent<boolean>) => void;
        /**
          * @deprecated use `toggle`
         */
        "onUiToggle"?: (event: UiPanelCustomEvent<{ expanded: boolean }>) => void;
        /**
          * Border radius of the panel
          * @default 'md'
         */
        "rounded"?: PanelRounded;
        /**
          * Size of the panel
          * @default 'md'
         */
        "size"?: PanelSize;
        /**
          * Keeps header visible while scrolling panel content
          * @default false
         */
        "stickyHeader"?: boolean;
        /**
          * Visual variant of the panel
          * @default 'default'
         */
        "variant"?: PanelVariant;
    }
    interface UiToast {
        "defaultDuration"?: number;
        "maxVisible"?: number;
        "onToastClose"?: (event: UiToastCustomEvent<ToastLifecycleDetail>) => void;
        "onToastShow"?: (event: UiToastCustomEvent<ToastLifecycleDetail>) => void;
        "pauseOnHover"?: boolean;
        "stackGap"?: number;
        "swipeDismiss"?: boolean;
    }
    interface UiToggle {
        "checked"?: boolean;
        /**
          * @default false
         */
        "defaultChecked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onToggleChange"?: (event: UiToggleCustomEvent<boolean>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface UiBadgeAttributes {
        "variant": BadgeVariant;
        "color": BadgeColor;
        "size": BadgeSize;
        "shape": BadgeShape;
        "dot": boolean;
        "removable": boolean;
        "disabled": boolean;
    }
    interface UiBreadcrumbAttributes {
        "items": string;
        "separator": BreadcrumbSeparator;
        "maxItems": string;
        "itemsBeforeCollapse": number;
        "itemsAfterCollapse": number;
        "disabled": boolean;
    }
    interface UiButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "animated": boolean;
        "rounded": ButtonRounded;
        "iconLeft": IconName;
        "iconRight": IconName;
        "icon": IconName;
    }
    interface UiButtonGroupAttributes {
        "variant": ButtonGroupVariant;
        "size": ButtonGroupSize;
        "segmented": boolean;
        "orientation": ButtonGroupOrientation;
        "gap": 'xs' | 'sm' | 'md' | 'lg' | 'none';
        "fullWidth": boolean;
        "disabled": boolean;
        "rounded": ButtonRounded;
        "buttons": string;
        "buttonLoading": boolean;
        "buttonAnimated": boolean;
        "buttonFullWidth": boolean;
        "selectionMode": 'none' | 'single' | 'multiple';
        "value": string | string[];
    }
    interface UiCheckboxAttributes {
        "checked": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
        "label": string;
    }
    interface UiDatePickerAttributes {
        "mode": DatePickerMode;
        "placeholder": string;
        "disabled": boolean;
        "loading": boolean;
        "readonly": boolean;
        "open": boolean;
        "defaultOpen": boolean;
        "minYear": number;
        "maxYear": number;
        "showIcon": boolean;
        "iconOnly": boolean;
        "showActions": boolean;
        "search": boolean;
        "icon": string;
        "label": string;
        "debounce": number;
    }
    interface UiDropdownAttributes {
        "value": string;
        "defaultValue": string;
        "mode": DropdownMode;
        "variant": DropdownVariant;
        "placeholder": string;
        "label": string;
        "disabled": boolean;
        "loading": boolean;
        "searchable": boolean;
        "clearable": boolean;
        "open": boolean;
        "minWidth": string;
        "maxWidth": string;
        "maxHeight": string;
        "selectAll": boolean;
    }
    interface UiIconAttributes {
        "name": IconName;
        "size": 'sm' | 'md' | 'lg';
        "stroke": number;
        "color": string;
    }
    interface UiInputAttributes {
        "value": string;
        "placeholder": string;
        "label": string;
        "disabled": boolean;
        "type": 'text' | 'number';
        "rounded": 'xs' | 'sm' | 'md' | 'xl';
        "icon": string;
        "iconAriaLabel": string;
    }
    interface UiPanelAttributes {
        "variant": PanelVariant;
        "size": PanelSize;
        "rounded": PanelRounded;
        "collapsible": boolean;
        "expanded": boolean;
        "loading": boolean;
        "disabled": boolean;
        "stickyHeader": boolean;
        "lazy": boolean;
    }
    interface UiToastAttributes {
        "maxVisible": number;
        "defaultDuration": number;
        "pauseOnHover": boolean;
        "stackGap": number;
        "swipeDismiss": boolean;
    }
    interface UiToggleAttributes {
        "checked": boolean;
        "defaultChecked": boolean;
        "disabled": boolean;
        "size": 'sm' | 'md' | 'lg';
    }

    interface IntrinsicElements {
        "ui-badge": Omit<UiBadge, keyof UiBadgeAttributes> & { [K in keyof UiBadge & keyof UiBadgeAttributes]?: UiBadge[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `attr:${K}`]?: UiBadgeAttributes[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `prop:${K}`]?: UiBadge[K] };
        "ui-breadcrumb": Omit<UiBreadcrumb, keyof UiBreadcrumbAttributes> & { [K in keyof UiBreadcrumb & keyof UiBreadcrumbAttributes]?: UiBreadcrumb[K] } & { [K in keyof UiBreadcrumb & keyof UiBreadcrumbAttributes as `attr:${K}`]?: UiBreadcrumbAttributes[K] } & { [K in keyof UiBreadcrumb & keyof UiBreadcrumbAttributes as `prop:${K}`]?: UiBreadcrumb[K] };
        "ui-button": Omit<UiButton, keyof UiButtonAttributes> & { [K in keyof UiButton & keyof UiButtonAttributes]?: UiButton[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `attr:${K}`]?: UiButtonAttributes[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `prop:${K}`]?: UiButton[K] };
        "ui-button-group": Omit<UiButtonGroup, keyof UiButtonGroupAttributes> & { [K in keyof UiButtonGroup & keyof UiButtonGroupAttributes]?: UiButtonGroup[K] } & { [K in keyof UiButtonGroup & keyof UiButtonGroupAttributes as `attr:${K}`]?: UiButtonGroupAttributes[K] } & { [K in keyof UiButtonGroup & keyof UiButtonGroupAttributes as `prop:${K}`]?: UiButtonGroup[K] };
        "ui-checkbox": Omit<UiCheckbox, keyof UiCheckboxAttributes> & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes]?: UiCheckbox[K] } & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes as `attr:${K}`]?: UiCheckboxAttributes[K] } & { [K in keyof UiCheckbox & keyof UiCheckboxAttributes as `prop:${K}`]?: UiCheckbox[K] };
        "ui-date-picker": Omit<UiDatePicker, keyof UiDatePickerAttributes> & { [K in keyof UiDatePicker & keyof UiDatePickerAttributes]?: UiDatePicker[K] } & { [K in keyof UiDatePicker & keyof UiDatePickerAttributes as `attr:${K}`]?: UiDatePickerAttributes[K] } & { [K in keyof UiDatePicker & keyof UiDatePickerAttributes as `prop:${K}`]?: UiDatePicker[K] };
        "ui-dropdown": Omit<UiDropdown, keyof UiDropdownAttributes> & { [K in keyof UiDropdown & keyof UiDropdownAttributes]?: UiDropdown[K] } & { [K in keyof UiDropdown & keyof UiDropdownAttributes as `attr:${K}`]?: UiDropdownAttributes[K] } & { [K in keyof UiDropdown & keyof UiDropdownAttributes as `prop:${K}`]?: UiDropdown[K] };
        "ui-icon": Omit<UiIcon, keyof UiIconAttributes> & { [K in keyof UiIcon & keyof UiIconAttributes]?: UiIcon[K] } & { [K in keyof UiIcon & keyof UiIconAttributes as `attr:${K}`]?: UiIconAttributes[K] } & { [K in keyof UiIcon & keyof UiIconAttributes as `prop:${K}`]?: UiIcon[K] } & OneOf<"name", UiIcon["name"], UiIconAttributes["name"]>;
        "ui-input": Omit<UiInput, keyof UiInputAttributes> & { [K in keyof UiInput & keyof UiInputAttributes]?: UiInput[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `attr:${K}`]?: UiInputAttributes[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `prop:${K}`]?: UiInput[K] };
        "ui-panel": Omit<UiPanel, keyof UiPanelAttributes> & { [K in keyof UiPanel & keyof UiPanelAttributes]?: UiPanel[K] } & { [K in keyof UiPanel & keyof UiPanelAttributes as `attr:${K}`]?: UiPanelAttributes[K] } & { [K in keyof UiPanel & keyof UiPanelAttributes as `prop:${K}`]?: UiPanel[K] };
        "ui-toast": Omit<UiToast, keyof UiToastAttributes> & { [K in keyof UiToast & keyof UiToastAttributes]?: UiToast[K] } & { [K in keyof UiToast & keyof UiToastAttributes as `attr:${K}`]?: UiToastAttributes[K] } & { [K in keyof UiToast & keyof UiToastAttributes as `prop:${K}`]?: UiToast[K] };
        "ui-toggle": Omit<UiToggle, keyof UiToggleAttributes> & { [K in keyof UiToggle & keyof UiToggleAttributes]?: UiToggle[K] } & { [K in keyof UiToggle & keyof UiToggleAttributes as `attr:${K}`]?: UiToggleAttributes[K] } & { [K in keyof UiToggle & keyof UiToggleAttributes as `prop:${K}`]?: UiToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * UI Badge Component
             * Modern badge component with multiple variants, colors, and sizes
             * Supports icon slot, dot mode, and removable functionality
             * @event remove - Emitted when the remove button is clicked
             */
            "ui-badge": LocalJSX.IntrinsicElements["ui-badge"] & JSXBase.HTMLAttributes<HTMLUiBadgeElement>;
            "ui-breadcrumb": LocalJSX.IntrinsicElements["ui-breadcrumb"] & JSXBase.HTMLAttributes<HTMLUiBreadcrumbElement>;
            /**
             * UI Button Component
             * Modern button component with shadcn/ui inspired variants
             * Supports multiple sizes, states, and animations
             * @event uiClick - Emitted when button is clicked (not disabled/loading)
             * @event uiFocus - Emitted when button receives focus
             * @event uiBlur - Emitted when button loses focus
             */
            "ui-button": LocalJSX.IntrinsicElements["ui-button"] & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            /**
             * UI ButtonGroup Component
             * Groups buttons together with layout control and selection logic
             * Composes existing Button components without duplicating logic
             * @event uiChange - Emitted when selection changes (if selectionMode is not 'none')
             * @event uiClick - Proxy for child button click events (optional)
             */
            "ui-button-group": LocalJSX.IntrinsicElements["ui-button-group"] & JSXBase.HTMLAttributes<HTMLUiButtonGroupElement>;
            "ui-checkbox": LocalJSX.IntrinsicElements["ui-checkbox"] & JSXBase.HTMLAttributes<HTMLUiCheckboxElement>;
            "ui-date-picker": LocalJSX.IntrinsicElements["ui-date-picker"] & JSXBase.HTMLAttributes<HTMLUiDatePickerElement>;
            "ui-dropdown": LocalJSX.IntrinsicElements["ui-dropdown"] & JSXBase.HTMLAttributes<HTMLUiDropdownElement>;
            "ui-icon": LocalJSX.IntrinsicElements["ui-icon"] & JSXBase.HTMLAttributes<HTMLUiIconElement>;
            "ui-input": LocalJSX.IntrinsicElements["ui-input"] & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-panel": LocalJSX.IntrinsicElements["ui-panel"] & JSXBase.HTMLAttributes<HTMLUiPanelElement>;
            "ui-toast": LocalJSX.IntrinsicElements["ui-toast"] & JSXBase.HTMLAttributes<HTMLUiToastElement>;
            "ui-toggle": LocalJSX.IntrinsicElements["ui-toggle"] & JSXBase.HTMLAttributes<HTMLUiToggleElement>;
        }
    }
}
